version: "3.9"

services:
  apiserver:
    image: ghcr.io/viswanathbalusu/agrothon:latest
    env_file:
      # Should be filled up and should be kept in the same directory
      - agrothon.env
    ports:
      # Mapping Ports, Make sure you map them correctly
      - "8000:8000"
    expose:
      - "8000"
    restart: unless-stopped
  tgbot:
    image: ghcr.io/viswanathbalusu/agrothon:latest
    env_file:
      - agrothon.env
    depends_on:
      - apiserver
    command: agrothon